Search.setIndex({
    objects: {},
    terms: {
        all: 2,
        just: [2, 5],
        global: 2,
        gquilt: 3,
        file: [0, 2],
        follow: 5,
        fine: 4,
        yet: 0,
        ground: 0,
        xml: 2,
        access: [2, 5],
        onli: 2,
        locat: 2,
        thank: 5,
        fix: [6, 0, 2],
        layman: [0, 2],
        should: 2,
        ebuild: 0,
        add: 2,
        appli: 0,
        main: 0,
        liter: [3, 1],
        contribut: 5,
        simplest: 4,
        util: [0, 7, 3],
        upstream: 0,
        report: [0, 5],
        name: 5,
        like: 5,
        edit: 2,
        docutil: [3, 1],
        drop: [0, 5],
        manual: [0, 2],
        method: [4, 2],
        separ: 0,
        easili: 2,
        either: [0, 2],
        wish: 4,
        found: 4,
        manag: [0, 2],
        depend: 3,
        gfx: [0, 1, 7],
        set: 2,
        quilt: 3,
        jnrow: [6, 2],
        some: 5,
        sync: 2,
        see: [2, 5],
        mirror: 2,
        download: [6, 0],
        peter: 3,
        index: 0,
        rsync: 2,
        wholeheartedli: 5,
        databas: 2,
        section: 2,
        find: 0,
        content: [0, 4],
        state: 0,
        version: [3, 1],
        proj: 2,
        overlai: [6, 0, 4, 2, 5],
        net: 3,
        bird: 5,
        integr: [0, 2],
        earlier: 2,
        run: [6, 2],
        ast: 5,
        layman2: 2,
        portdir_overlai: 2,
        repositori: [2, 5],
        org: 2,
        stage: 0,
        reflect: 0,
        search: 0,
        would: 4,
        page: [0, 2],
        etc: 2,
        isn: 3,
        forgotten: 5,
        com: [6, 1],
        jami: 5,
        first: 2,
        oper: 2,
        "final": 2,
        directli: 2,
        onc: 2,
        rachel: 5,
        prefer: 4,
        www: 2,
        leon: 5,
        echo: 2,
        email: [0, 4, 5],
        contributor: [0, 5],
        instal: [0, 2, 3],
        oilman: [0, 2],
        txt: 2,
        open: 4,
        your: [2, 5],
        bigpond: 3,
        git: [6, 2],
        span: [3, 1],
        wai: 4,
        support: [1, 2],
        patch: [0, 5],
        submit: 0,
        mercuri: 3,
        call: 2,
        includ: 5,
        "var": 2,
        tell: 2,
        option: 3,
        peopl: 5,
        about: 4,
        specifi: 2,
        idea: [0, 5],
        muennich: 1,
        holm: 5,
        newer: 2,
        bug: [0, 1, 5, 3],
        eix: 2,
        work: 2,
        sxiv: 1,
        dev: [0, 7, 3],
        histori: 5,
        project: 6,
        can: [6, 0, 2, 5],
        savedconfig: 1,
        problem: [0, 4],
        purpos: 0,
        fetch: 2,
        pre: [3, 1, 5],
        have: [0, 5],
        ani: 0,
        indic: 0,
        packag: [0, 7, 2],
        list: [2, 5],
        conf: 2,
        tabl: 0,
        tarbal: 6,
        mai: 2,
        welcom: 0,
        lib: 2,
        rather: 2,
        media: [0, 1, 7],
        make: 2,
        detail: 2,
        same: 2,
        note: [2, 5],
        also: 6,
        need: 2,
        contact: [0, 4],
        you: [6, 0, 4, 2, 5],
        document: 0,
        eclass: 1,
        updat: [2, 5],
        http: [3, 1, 2],
        gentoo: [0, 2],
        clone: [6, 2],
        who: 5,
        william: 3,
        befor: 2,
        user: [3, 2],
        date: 5,
        "class": [3, 1],
        portag: 2,
        repo: 2,
        github: [6, 1, 4, 5],
        move: 5,
        apologis: 5,
        issu: [0, 4],
        perform: 2,
        exampl: 2,
        command: 2,
        thi: [6, 0, 4, 2, 5],
        time: 2,
        ashton: 5,
        fallback: 4
    },
    objtypes: {},
    titles: ["Welcome to fixes-overlay&#8217;s documentation!", "<tt class=\"docutils literal docutils literal\"><span class=\"pre\">media-gfx</span></tt>", "Installation", "<tt class=\"docutils literal docutils literal\"><span class=\"pre\">dev-util</span></tt>", "Contact", "Contributors", "Download", "Packages"],
    objnames: {},
    filenames: ["index", "packages/media-gfx", "installation", "packages/dev-util", "contact", "thanks", "download", "packages"]
})
